# Exploratory Data Analysis for NBA Lineup Prediction and Hidden Patterns

This notebook organizes the data exploration steps from the raw CSV file and then implements several additional views to uncover hidden patterns. We aim to understand:

- **Lineup stability and variation** over time
- **Frequency of player appearances** in different positions (home_0 to home_4)
- **Outcome analysis** by lineup
- **Common matchups:** which home players appear most frequently against certain away lineups

These insights can guide further feature engineering to improve our predictive model.

In [33]:
# Import necessary libraries
import pandas as pd
import numpy as np
import glob
import os

import matplotlib.pyplot as plt
import seaborn as sns

# For warnings
import warnings
warnings.filterwarnings('ignore')

# Set display options for Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

pd.option_context('display.max_rows', None, 'display.max_columns', None)

## 1. Load and Inspect the Raw Data

Here we load a sample raw CSV file (2007 season) and inspect its contents.

In [34]:
# Define the folder containing the CSV files (update the path as needed)
data_folder = "../data"  # Replace with your actual data folder path

# Load all CSV files from 2007 to 2015
csv_files = sorted(glob.glob(os.path.join(data_folder, "matchups-20*.csv")))
dfs = []
for file in csv_files:
    print(f"Loading {file}")
    df = pd.read_csv(file)
    dfs.append(df)

df_all_years = pd.concat(dfs, ignore_index=True)

print("Dataset loaded with shape:", df_all_years.shape)
display(df_all_years.head())

Loading ../data\matchups-2007.csv
Loading ../data\matchups-2008.csv
Loading ../data\matchups-2009.csv
Loading ../data\matchups-2010.csv
Loading ../data\matchups-2011.csv
Loading ../data\matchups-2012.csv
Loading ../data\matchups-2013.csv
Loading ../data\matchups-2014.csv
Loading ../data\matchups-2015.csv
Dataset loaded with shape: (236912, 53)

,game,season,home_team,away_team,starting_min,end_min,home_0,home_1,home_2,home_3,home_4,away_0,away_1,away_2,away_3,away_4,fga_home,fta_home,fgm_home,fga_2_home,fgm_2_home,fga_3_home,fgm_3_home,ast_home,blk_home,pf_home,reb_home,dreb_home,oreb_home,to_home,pts_home,pct_home,pct_2_home,pct_3_home,fga_visitor,fta_visitor,fgm_visitor,fga_2_visitor,fgm_2_visitor,fga_3_visitor,fgm_3_visitor,ast_visitor,blk_visitor,pf_visitor,reb_visitor,dreb_visitor,oreb_visitor,to_visitor,pts_visitor,pct_visitor,pct_2_visitor,pct_3_visitor,outcome
0,200610310LAL,2007,LAL,PHO,0,5,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Boris Diaw,Kurt Thomas,Raja Bell,Shawn Marion,Steve Nash,10,4,4,7,3,3,1,3,0,1,1,1,0,1,9,0.400000,0.428571,0.333333,11,1,10,8,8,3,2,6,0,0,7,7,0,1,22,0.909091,1.00,0.666667,-1
1,200610310LAL,2007,LAL,PHO,6,7,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,3,0,2,2,2,1,0,1,0,0,2,2,0,2,4,0.666667,1.000000,0.000000,6,0,4,4,3,2,1,4,0,0,1,1,0,0,9,0.666667,0.75,0.500000,-1
2,200610310LAL,2007,LAL,PHO,8,9,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,4,0,2,4,2,0,0,2,1,1,2,1,1,2,4,0.500000,0.500000,0.000000,2,2,1,2,1,0,0,1,0,0,1,1,0,1,2,0.500000,0.50,0.000000,1
3,200610310LAL,2007,LAL,PHO,10,10,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,2,0,2,2,2,0,0,1,0,0,0,0,0,0,4,1.000000,1.000000,0.000000,2,0,1,0,0,2,1,1,0,0,1,0,1,1,3,0.500000,0.00,0.500000,1
4,200610310LAL,2007,LAL,PHO,11,11,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Vladimir Radmanovic,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,2,0,1,2,1,0,0,1,0,1,0,0,0,0,2,0.500000,0.500000,0.000000,1,0,1,1,1,0,0,1,0,1,1,1,0,1,2,1.000000,1.00,0.000000,-1

## 2. Filter to Allowed Features and Create a Date Column

We will filter the data to include only the allowed features and then extract a proper date from the `game` column.

In [35]:
# Define the allowed features
allowed_features = [
    'game', 'season', 'home_team', 'away_team', 'starting_min',
    'home_0', 'home_1', 'home_2', 'home_3', 'home_4',
    'away_0', 'away_1', 'away_2', 'away_3', 'away_4',
    'outcome'  
]

# Filter the dataframe
df_filtered = df_all_years[allowed_features].copy()

# Create a date column from the first 8 characters of the 'game' column
df_filtered['date'] = pd.to_datetime(df_filtered['game'].str[:8], format='%Y%m%d')

df_filtered

,game,season,home_team,away_team,starting_min,home_0,home_1,home_2,home_3,home_4,away_0,away_1,away_2,away_3,away_4,outcome,date
0,200610310LAL,2007,LAL,PHO,0,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Boris Diaw,Kurt Thomas,Raja Bell,Shawn Marion,Steve Nash,-1,2006-10-31
1,200610310LAL,2007,LAL,PHO,6,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,-1,2006-10-31
2,200610310LAL,2007,LAL,PHO,8,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,1,2006-10-31
3,200610310LAL,2007,LAL,PHO,10,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,1,2006-10-31
4,200610310LAL,2007,LAL,PHO,11,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Vladimir Radmanovic,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,-1,2006-10-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236907,201504050NYK,2015,NYK,PHI,35,Jason Smith,Quincy Acy,Ricky Ledo,Shane Larkin,Tim Hardaway,Henry Sims,Hollis Thompson,JaKarr Sampson,Jason Richardson,Jerami Grant,-1,2015-04-05
236908,201504050NYK,2015,NYK,PHI,39,Jason Smith,Langston Galloway,Quincy Acy,Ricky Ledo,Tim Hardaway,Henry Sims,Hollis Thompson,JaKarr Sampson,Jason Richardson,Jerami Grant,-1,2015-04-05
236909,201504050NYK,2015,NYK,PHI,40,Jason Smith,Langston Galloway,Quincy Acy,Ricky Ledo,Tim Hardaway,Furkan Aldemir,Hollis Thompson,JaKarr Sampson,Jason Richardson,Nerlens Noel,-1,2015-04-05
236910,201504050NYK,2015,NYK,PHI,42,Andrea Bargnani,Jason Smith,Lance Thomas,Langston Galloway,Shane Larkin,Furkan Aldemir,Ish Smith,Jerami Grant,Nerlens Noel,Robert Covington,-1,2015-04-05
236911,201504050NYK,2015,NYK,PHI,45,Andrea Bargnani,Jason Smith,Lance Thomas,Langston Galloway,Shane Larkin,Furkan Aldemir,Hollis Thompson,Ish Smith,Nerlens Noel,Robert Covington,1,2015-04-05

## 3. Create Lineup Tuples for Home and Away Teams

To explore lineup frequency and uniqueness, we create sorted tuples of players for both the home and away teams.

In [36]:
# Create lineup tuples (sorted alphabetically for consistency)
df_filtered['home_lineup'] = df_filtered[['home_0', 'home_1', 'home_2', 'home_3', 'home_4']].apply(lambda x: tuple(sorted(x)), axis=1)
df_filtered['away_lineup'] = df_filtered[['away_0', 'away_1', 'away_2', 'away_3', 'away_4']].apply(lambda x: tuple(sorted(x)), axis=1)

df_filtered[['game', 'home_lineup', 'away_lineup', 'date']]

,game,home_lineup,away_lineup,date
0,200610310LAL,"(Andrew Bynum, Lamar Odom, Luke Walton, Sasha Vujacic, Smush Parker)","(Boris Diaw, Kurt Thomas, Raja Bell, Shawn Marion, Steve Nash)",2006-10-31
1,200610310LAL,"(Andrew Bynum, Lamar Odom, Luke Walton, Sasha Vujacic, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",2006-10-31
2,200610310LAL,"(Lamar Odom, Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",2006-10-31
3,200610310LAL,"(Lamar Odom, Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)",2006-10-31
4,200610310LAL,"(Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker, Vladimir Radmanovic)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)",2006-10-31
...,...,...,...,...
236907,201504050NYK,"(Jason Smith, Quincy Acy, Ricky Ledo, Shane Larkin, Tim Hardaway)","(Henry Sims, Hollis Thompson, JaKarr Sampson, Jason Richardson, Jerami Grant)",2015-04-05
236908,201504050NYK,"(Jason Smith, Langston Galloway, Quincy Acy, Ricky Ledo, Tim Hardaway)","(Henry Sims, Hollis Thompson, JaKarr Sampson, Jason Richardson, Jerami Grant)",2015-04-05
236909,201504050NYK,"(Jason Smith, Langston Galloway, Quincy Acy, Ricky Ledo, Tim Hardaway)","(Furkan Aldemir, Hollis Thompson, JaKarr Sampson, Jason Richardson, Nerlens Noel)",2015-04-05
236910,201504050NYK,"(Andrea Bargnani, Jason Smith, Lance Thomas, Langston Galloway, Shane Larkin)","(Furkan Aldemir, Ish Smith, Jerami Grant, Nerlens Noel, Robert Covington)",2015-04-05
236911,201504050NYK,"(Andrea Bargnani, Jason Smith, Lance Thomas, Langston Galloway, Shane Larkin)","(Furkan Aldemir, Hollis Thompson, Ish Smith, Nerlens Noel, Robert Covington)",2015-04-05

## 4. Unique Lineup Counts per Game

We group by game and count how many unique home and away lineups were used.

In [5]:
# Count unique lineups per game
lineup_counts = df_filtered.groupby('game').agg(
    unique_home_lineups=('home_lineup', 'nunique'),
    unique_away_lineups=('away_lineup', 'nunique')
).reset_index()

lineup_counts

               game  unique_home_lineups  unique_away_lineups
0      200610310LAL                   11                    9
1      200610310MIA                   11                   16
2      200611010BOS                   19                   17
3      200611010CHA                   16                   15
4      200611010CLE                   12                   10
...             ...                  ...                  ...
10823  201504150MIN                   15                   14
10824  201504150NOP                   14                   16
10825  201504150NYK                   12                   14
10826  201504150PHI                    9                    2
10827  201504150TOR                    8                    8

[10828 rows x 3 columns]

In [37]:
unique_games = df_all_years['game'].nunique()
print("Total unique games:", unique_games)

Total unique games: 10828

In [38]:
df_filtered

,game,season,home_team,away_team,starting_min,home_0,home_1,home_2,home_3,home_4,away_0,away_1,away_2,away_3,away_4,outcome,date,home_lineup,away_lineup
0,200610310LAL,2007,LAL,PHO,0,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Boris Diaw,Kurt Thomas,Raja Bell,Shawn Marion,Steve Nash,-1,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Sasha Vujacic, Smush Parker)","(Boris Diaw, Kurt Thomas, Raja Bell, Shawn Marion, Steve Nash)"
1,200610310LAL,2007,LAL,PHO,6,Andrew Bynum,Lamar Odom,Luke Walton,Sasha Vujacic,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,-1,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Sasha Vujacic, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)"
2,200610310LAL,2007,LAL,PHO,8,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Amar'e Stoudemire,Leandro Barbosa,Raja Bell,Shawn Marion,Steve Nash,1,2006-10-31,"(Lamar Odom, Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)"
3,200610310LAL,2007,LAL,PHO,10,Lamar Odom,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,1,2006-10-31,"(Lamar Odom, Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)"
4,200610310LAL,2007,LAL,PHO,11,Luke Walton,Maurice Evans,Ronny Turiaf,Smush Parker,Vladimir Radmanovic,Boris Diaw,James Jones,Kurt Thomas,Leandro Barbosa,Marcus Banks,-1,2006-10-31,"(Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker, Vladimir Radmanovic)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236907,201504050NYK,2015,NYK,PHI,35,Jason Smith,Quincy Acy,Ricky Ledo,Shane Larkin,Tim Hardaway,Henry Sims,Hollis Thompson,JaKarr Sampson,Jason Richardson,Jerami Grant,-1,2015-04-05,"(Jason Smith, Quincy Acy, Ricky Ledo, Shane Larkin, Tim Hardaway)","(Henry Sims, Hollis Thompson, JaKarr Sampson, Jason Richardson, Jerami Grant)"
236908,201504050NYK,2015,NYK,PHI,39,Jason Smith,Langston Galloway,Quincy Acy,Ricky Ledo,Tim Hardaway,Henry Sims,Hollis Thompson,JaKarr Sampson,Jason Richardson,Jerami Grant,-1,2015-04-05,"(Jason Smith, Langston Galloway, Quincy Acy, Ricky Ledo, Tim Hardaway)","(Henry Sims, Hollis Thompson, JaKarr Sampson, Jason Richardson, Jerami Grant)"
236909,201504050NYK,2015,NYK,PHI,40,Jason Smith,Langston Galloway,Quincy Acy,Ricky Ledo,Tim Hardaway,Furkan Aldemir,Hollis Thompson,JaKarr Sampson,Jason Richardson,Nerlens Noel,-1,2015-04-05,"(Jason Smith, Langston Galloway, Quincy Acy, Ricky Ledo, Tim Hardaway)","(Furkan Aldemir, Hollis Thompson, JaKarr Sampson, Jason Richardson, Nerlens Noel)"
236910,201504050NYK,2015,NYK,PHI,42,Andrea Bargnani,Jason Smith,Lance Thomas,Langston Galloway,Shane Larkin,Furkan Aldemir,Ish Smith,Jerami Grant,Nerlens Noel,Robert Covington,-1,2015-04-05,"(Andrea Bargnani, Jason Smith, Lance Thomas, Langston Galloway, Shane Larkin)","(Furkan Aldemir, Ish Smith, Jerami Grant, Nerlens Noel, Robert Covington)"
236911,201504050NYK,2015,NYK,PHI,45,Andrea Bargnani,Jason Smith,Lance Thomas,Langston Galloway,Shane Larkin,Furkan Aldemir,Hollis Thompson,Ish Smith,Nerlens Noel,Robert Covington,1,2015-04-05,"(Andrea Bargnani, Jason Smith, Lance Thomas, Langston Galloway, Shane Larkin)","(Furkan Aldemir, Hollis Thompson, Ish Smith, Nerlens Noel, Robert Covington)"

## 5. Most Frequently Used Lineups per Game

We now identify the most frequently used home and away lineups for each game.

In [8]:
# Count occurrences of each lineup combination
lineup_usage = df_filtered.groupby(['game', 'home_team', 'away_team', 'date', 'home_lineup', 'away_lineup']).size().reset_index(name='count')

# For each game, select the lineup combination with the highest count
most_used_lineups = lineup_usage.sort_values(['game', 'count'], ascending=[True, False])

most_used_lineups.head()

,game,home_team,away_team,date,home_lineup,away_lineup,count
2,200610310LAL,LAL,PHO,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Maurice Evans, Smush Parker)","(Boris Diaw, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",2
3,200610310LAL,LAL,PHO,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Maurice Evans, Smush Parker)","(Kurt Thomas, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",2
8,200610310LAL,LAL,PHO,2006-10-31,"(Brian Cook, Jordan Farmar, Lamar Odom, Sasha Vujacic, Vladimir Radmanovic)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)",2
0,200610310LAL,LAL,PHO,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Maurice Evans, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",1
1,200610310LAL,LAL,PHO,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Maurice Evans, Smush Parker)","(Boris Diaw, Kurt Thomas, Raja Bell, Shawn Marion, Steve Nash)",1

## 6. Additional Views and Analyses

In this section, we implement several new views to uncover hidden patterns:

1. **Frequency Analysis by Player Position:** How often does each player appear in a given home position (home_0, home_1, etc.)?
2. **Outcome Analysis by Home Lineup:** What are the win/loss outcomes (or average outcome) for different home lineups?
3. **Common Home Players Against Specific Away Lineups:** Which home players are most frequently used against a given away lineup?
4. **Lineup Variation Over Time:** How does the number of unique lineups change over time?

### 6.1 Frequency Analysis by Player Position

In [39]:
# Analyze frequency of players in each home position
for pos in ['home_0', 'home_1', 'home_2', 'home_3', 'home_4']:
    print(f"Frequency for {pos}:")
    print(df_filtered[pos].value_counts().head(10))
    print("---")

Frequency for home_0:
home_0
Andre Iguodala       5150
Al Jefferson         4492
Amar'e Stoudemire    3804
Boris Diaw           3502
Al Horford           3340
Al Harrington        3129
Beno Udrih           2951
Andrew Bogut         2652
Anderson Varejao     2650
Andray Blatche       2532
Name: count, dtype: int64
---
Frequency for home_1:
home_1
Dwyane Wade        2468
Carmelo Anthony    2446
David West         2433
Dirk Nowitzki      2258
Dwight Howard      2216
Andre Miller       2139
Deron Williams     2029
David Lee          1985
Kevin Durant       1983
Jamal Crawford     1982
Name: count, dtype: int64
---
Frequency for home_2:
home_2
LaMarcus Aldridge    2340
Josh Smith           2114
LeBron James         1864
J.R. Smith           1846
Kobe Bryant          1821
Jarrett Jack         1815
Deron Williams       1763
Paul Pierce          1761
Lamar Odom           1721
Mike Conley          1706
Name: count, dtype: int64
---
Frequency for home_3:
home_3
Tim Duncan       3281
Monta Ellis      2688
Rajon Rondo      2298
Pau Gasol        2104
LeBron James     2073
Shawn Marion     2069
Mike Dunleavy    2044
Paul Millsap     2041
Jason Terry      2011
Luol Deng        1991
Name: count, dtype: int64
---
Frequency for home_4:
home_4
Tony Parker       4478
Vince Carter      4332
Zach Randolph     4219
Tyson Chandler    3757
Trevor Ariza      3438
Steve Nash        3230
Tyreke Evans      3146
Thaddeus Young    3028
Udonis Haslem     3014
Zaza Pachulia     2985
Name: count, dtype: int64
---

### 6.2 Outcome Analysis by Home Lineup

We group by the home lineup and calculate the average outcome and the number of games for each unique lineup. (Note: The `outcome` column typically indicates win/loss; you may need to adjust if using different metrics.)

In [89]:
# Outcome analysis by home lineup with home team and season information
lineup_outcomes = df_filtered.groupby(['season', 'home_team', 'home_lineup']).agg(
    games=('game', 'count'),
    avg_outcome=('outcome', 'mean')
).reset_index()

# Display the top 10 lineups by number of games played
top_lineups = lineup_outcomes.sort_values('games', ascending=False)

In [94]:
lineup_outcomes.head(35).sort_values('games', ascending=False)

,season,home_team,home_lineup,games,avg_outcome
16,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Marvin Williams, Zaza Pachulia)",41,0.073171
12,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Marvin Williams, Salim Stoudamire)",7,-0.428571
4,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Josh Smith, Zaza Pachulia)",6,-0.333333
22,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Tyronn Lue, Zaza Pachulia)",5,-0.600000
14,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Marvin Williams, Solomon Jones)",5,-1.000000
18,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Salim Stoudamire, Zaza Pachulia)",4,0.500000
11,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Lorenzen Wright, Marvin Williams)",4,0.000000
9,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Marvin Williams, Zaza Pachulia)",4,-0.500000
29,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Solomon Jones, Tyronn Lue)",3,-1.000000
2,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Josh Smith, Marvin Williams)",3,-1.000000
33,2007,ATL,"(Anthony Johnson, Josh Childress, Salim Stoudamire, Shelden Williams, Solomon Jones)",3,0.333333
21,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Solomon Jones, Zaza Pachulia)",3,-0.333333
13,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Marvin Williams, Shelden Williams)",3,-1.000000
32,2007,ATL,"(Anthony Johnson, Josh Childress, Royal Ivey, Salim Stoudamire, Solomon Jones)",2,0.000000
1,2007,ATL,"(Anthony Johnson, Esteban Batista, Marvin Williams, Royal Ivey, Shelden Williams)",2,0.000000
3,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Josh Smith, Solomon Jones)",2,0.000000
5,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Lorenzen Wright, Marvin Williams)",2,1.000000
7,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Marvin Williams, Solomon Jones)",2,-1.000000
6,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Marvin Williams, Shelden Williams)",2,-1.000000
17,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Salim Stoudamire, Solomon Jones)",2,0.000000
31,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Tyronn Lue, Zaza Pachulia)",2,-1.000000
0,2007,ATL,"(Anthony Johnson, Esteban Batista, Josh Smith, Royal Ivey, Solomon Jones)",1,-1.000000
8,2007,ATL,"(Anthony Johnson, Joe Johnson, Josh Childress, Marvin Williams, Tyronn Lue)",1,-1.000000
15,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Marvin Williams, Tyronn Lue)",1,1.000000
10,2007,ATL,"(Anthony Johnson, Joe Johnson, Marvin Williams, Solomon Jones, Speedy Claxton)",1,-1.000000
20,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Shelden Williams, Zaza Pachulia)",1,1.000000
19,2007,ATL,"(Anthony Johnson, Josh Childress, Josh Smith, Shelden Williams, Solomon Jones)",1,-1.000000
26,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Shelden Williams, Tyronn Lue)",1,-1.000000
25,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Salim Stoudamire, Zaza Pachulia)",1,1.000000
24,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Salim Stoudamire, Solomon Jones)",1,1.000000
23,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Salim Stoudamire, Shelden Williams)",1,-1.000000
30,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Solomon Jones, Zaza Pachulia)",1,-1.000000
28,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Solomon Jones, Speedy Claxton)",1,-1.000000
27,2007,ATL,"(Anthony Johnson, Josh Childress, Marvin Williams, Shelden Williams, Zaza Pachulia)",1,-1.000000
34,2007,ATL,"(Anthony Johnson, Josh Childress, Salim Stoudamire, Shelden Williams, Tyronn Lue)",1,1.000000

In [95]:
lineup_outcomes.count()

season         60036
home_team      60036
home_lineup    60036
games          60036
avg_outcome    60036
dtype: int64

### 6.3 Most Common Home Players Against Specific Away Lineups

For each unique away lineup, we analyze which home players appear most frequently. Here we melt the home player columns into one long format and then group by away lineup and player.

In [97]:
# Melt the home player columns to analyze individual player frequency per team per season
home_players = df_filtered.melt(
    id_vars=['season', 'game', 'home_team', 'away_lineup', 'date'],
    value_vars=['home_0', 'home_1', 'home_2', 'home_3', 'home_4'],
    var_name='home_position',
    value_name='home_player'
)

# Count the frequency of each home player per away lineup, per team, and per season
common_players_vs_away = home_players.groupby(['season', 'home_team', 'away_lineup', 'home_player']).size().reset_index(name='count')

# Sort by frequency of occurrence
common_players_vs_away = common_players_vs_away.sort_values(['season', 'home_team', 'away_lineup', 'count'], ascending=[True, True, True, False])

In [98]:
common_players_vs_away

,season,home_team,away_lineup,home_player,count
1,2007,ATL,"(Aaron Williams, Chris Kaman, Cuttino Mobley, Daniel Ewing, Tim Thomas)",Josh Childress,5
2,2007,ATL,"(Aaron Williams, Chris Kaman, Cuttino Mobley, Daniel Ewing, Tim Thomas)",Lorenzen Wright,5
4,2007,ATL,"(Aaron Williams, Chris Kaman, Cuttino Mobley, Daniel Ewing, Tim Thomas)",Salim Stoudamire,4
7,2007,ATL,"(Aaron Williams, Chris Kaman, Cuttino Mobley, Daniel Ewing, Tim Thomas)",Zaza Pachulia,4
3,2007,ATL,"(Aaron Williams, Chris Kaman, Cuttino Mobley, Daniel Ewing, Tim Thomas)",Marvin Williams,3
...,...,...,...,...,...
745793,2015,WAS,"(Langston Galloway, Lou Amundson, Quincy Acy, Ricky Ledo, Shane Larkin)",Bradley Beal,1
745794,2015,WAS,"(Langston Galloway, Lou Amundson, Quincy Acy, Ricky Ledo, Shane Larkin)",John Wall,1
745795,2015,WAS,"(Langston Galloway, Lou Amundson, Quincy Acy, Ricky Ledo, Shane Larkin)",Kris Humphries,1
745796,2015,WAS,"(Langston Galloway, Lou Amundson, Quincy Acy, Ricky Ledo, Shane Larkin)",Marcin Gortat,1
745797,2015,WAS,"(Langston Galloway, Lou Amundson, Quincy Acy, Ricky Ledo, Shane Larkin)",Otto Porter,1

In [43]:
# Melt the home player columns to analyze individual player frequency
home_players = df_filtered.melt(
    id_vars=['game', 'away_lineup', 'date'],
    value_vars=['home_0', 'home_1', 'home_2', 'home_3', 'home_4'],
    var_name='home_position',
    value_name='home_player'
)

# Count the frequency of each home player per away lineup
common_players_vs_away = home_players.groupby(['away_lineup', 'home_player']).size().reset_index(name='count')

# Sort the entire DataFrame by away_lineup and count descending
sorted_common_players = common_players_vs_away.sort_values(['away_lineup', 'count'], ascending=[True, False])

# Display the entire sorted DataFrame
sorted_common_players.head(35)

,away_lineup,home_player,count
0,"(A.J. Price, Alex Len, Archie Goodwin, Eric Bledsoe, Marcus Morris)",Corey Brewer,2
2,"(A.J. Price, Alex Len, Archie Goodwin, Eric Bledsoe, Marcus Morris)",Jason Terry,2
4,"(A.J. Price, Alex Len, Archie Goodwin, Eric Bledsoe, Marcus Morris)",Pablo Prigioni,2
5,"(A.J. Price, Alex Len, Archie Goodwin, Eric Bledsoe, Marcus Morris)",Trevor Ariza,2
1,"(A.J. Price, Alex Len, Archie Goodwin, Eric Bledsoe, Marcus Morris)",Donatas Motiejunas,1
3,"(A.J. Price, Alex Len, Archie Goodwin, Eric Bledsoe, Marcus Morris)",Josh Smith,1
6,"(A.J. Price, Alex Len, Archie Goodwin, P.J. Tucker, T.J. Warren)",Arron Afflalo,1
7,"(A.J. Price, Alex Len, Archie Goodwin, P.J. Tucker, T.J. Warren)",CJ McCollum,1
8,"(A.J. Price, Alex Len, Archie Goodwin, P.J. Tucker, T.J. Warren)",Chris Kaman,1
9,"(A.J. Price, Alex Len, Archie Goodwin, P.J. Tucker, T.J. Warren)",Dorell Wright,1
10,"(A.J. Price, Alex Len, Archie Goodwin, P.J. Tucker, T.J. Warren)",Steve Blake,1
11,"(A.J. Price, Alex Len, Brandan Wright, Reggie Bullock, T.J. Warren)",CJ McCollum,1
12,"(A.J. Price, Alex Len, Brandan Wright, Reggie Bullock, T.J. Warren)",Chris Kaman,1
13,"(A.J. Price, Alex Len, Brandan Wright, Reggie Bullock, T.J. Warren)",Dorell Wright,1
14,"(A.J. Price, Alex Len, Brandan Wright, Reggie Bullock, T.J. Warren)",Meyers Leonard,1
15,"(A.J. Price, Alex Len, Brandan Wright, Reggie Bullock, T.J. Warren)",Steve Blake,1
16,"(A.J. Price, Alex Len, Eric Bledsoe, Gerald Green, P.J. Tucker)",Damian Lillard,1
17,"(A.J. Price, Alex Len, Eric Bledsoe, Gerald Green, P.J. Tucker)",Dorell Wright,1
18,"(A.J. Price, Alex Len, Eric Bledsoe, Gerald Green, P.J. Tucker)",LaMarcus Aldridge,1
19,"(A.J. Price, Alex Len, Eric Bledsoe, Gerald Green, P.J. Tucker)",Nicolas Batum,1
20,"(A.J. Price, Alex Len, Eric Bledsoe, Gerald Green, P.J. Tucker)",Robin Lopez,1
21,"(A.J. Price, Alex Len, Gerald Green, Markieff Morris, T.J. Warren)",CJ McCollum,1
22,"(A.J. Price, Alex Len, Gerald Green, Markieff Morris, T.J. Warren)",Chris Kaman,1
23,"(A.J. Price, Alex Len, Gerald Green, Markieff Morris, T.J. Warren)",Damian Lillard,1
24,"(A.J. Price, Alex Len, Gerald Green, Markieff Morris, T.J. Warren)",Dorell Wright,1
25,"(A.J. Price, Alex Len, Gerald Green, Markieff Morris, T.J. Warren)",LaMarcus Aldridge,1
28,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",Chris Kaman,2
30,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",Dorell Wright,2
32,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",Steve Blake,2
26,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",Arron Afflalo,1
27,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",CJ McCollum,1
29,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",Damian Lillard,1
31,"(A.J. Price, Alex Len, Gerald Green, P.J. Tucker, T.J. Warren)",Nicolas Batum,1
33,"(A.J. Price, Alexey Shved, Chase Budinger, Dante Cunningham, Ronny Turiaf)",Draymond Green,1
34,"(A.J. Price, Alexey Shved, Chase Budinger, Dante Cunningham, Ronny Turiaf)",Harrison Barnes,1

## 7. Conclusions and Next Steps

We have now organized the initial exploratory code and extended our analysis with additional views:

- **Frequency by Position:** Reveals which players appear most frequently in each home position.
- **Outcome Analysis:** Shows the performance (win/loss average) of different home lineups.
- **Common Matchups:** Identifies which home players are used most often against particular away lineups.
- **Temporal Trends:** Examines lineup variation over time.

These insights can help guide further feature engineering—such as adding a "lineup stability" score, network centrality measures for player synergy, or clustering of lineups—to improve the accuracy, precision, and recall of our missing-player prediction model.

Feel free to extend the analysis by exploring additional correlations (e.g., linking player positions if that information is available externally) or by applying association rule mining to detect frequent player combinations.

Let's continue discussing how we can further manipulate these data tables to gain even deeper insights.

In [ ]:
lineup_outcomes.sort_values('games', ascending=False).head(10)

,home_team,home_lineup,games,avg_outcome
3766,BOS,"(Kendrick Perkins, Kevin Garnett, Paul Pierce, Rajon Rondo, Ray Allen)",524,0.045802
21292,IND,"(David West, George Hill, Lance Stephenson, Paul George, Roy Hibbert)",399,-0.007519
40198,OKC,"(Kendrick Perkins, Kevin Durant, Russell Westbrook, Serge Ibaka, Thabo Sefolosha)",345,-0.113043
546,ATL,"(Al Horford, Joe Johnson, Josh Smith, Marvin Williams, Mike Bibby)",334,-0.017964
26920,MEM,"(Marc Gasol, Mike Conley, O.J. Mayo, Rudy Gay, Zach Randolph)",316,-0.101266
40117,OKC,"(Jeff Green, Kevin Durant, Nenad Krstic, Russell Westbrook, Thabo Sefolosha)",294,-0.095238
46731,POR,"(Damian Lillard, LaMarcus Aldridge, Nicolas Batum, Robin Lopez, Wesley Matthews)",272,-0.095588
22554,LAC,"(Blake Griffin, Chris Paul, DeAndre Jordan, J.J. Redick, Matt Barnes)",263,-0.011407
24320,LAL,"(Derek Fisher, Kobe Bryant, Lamar Odom, Metta World Peace, Pau Gasol)",241,-0.219917
23633,LAL,"(Andrew Bynum, Derek Fisher, Kobe Bryant, Metta World Peace, Pau Gasol)",223,-0.219731

In [56]:
# Extract the starting lineup for each game (row with the smallest starting_min per game)
starting_lineups = df_filtered.sort_values('starting_min').groupby(['season', 'game']).first().reset_index()

# Group by season, home_team, and home_lineup to compute number of games and the average outcome
starting_lineup_stats = starting_lineups.groupby(['season', 'home_team', 'home_lineup']).agg(
    games_count=('game', 'count'),
    avg_outcome=('outcome', 'mean')
).reset_index()

# For each season and home_team, select the lineup with the maximum games_count (most frequently used lineup)
idx = starting_lineup_stats.groupby(['season', 'home_team'])['games_count'].idxmax()
most_common_starting_lineups = starting_lineup_stats.loc[idx].reset_index(drop=True)

# Sort results to see the most used lineups first
most_common_starting_lineups = most_common_starting_lineups.sort_values(['season', 'games_count'], ascending=[True, False])

# Display the result
print(most_common_starting_lineups)

     season home_team  \
16     2007       MIN
5      2007       DAL
20     2007       ORL
22     2007       PHO
3      2007       CHI
..      ...       ...
261    2015       ORL
257    2015       MIN
259    2015       NYK
244    2015       CHO
262    2015       PHI

                                                                                     home_lineup  \
16                        (Kevin Garnett, Mark Blount, Mike James, Ricky Davis, Trenton Hassell)
5                         (Devin Harris, Dirk Nowitzki, Erick Dampier, Jason Terry, Josh Howard)
20                        (Dwight Howard, Grant Hill, Hedo Turkoglu, Jameer Nelson, Tony Battie)
22                          (Amar'e Stoudemire, Boris Diaw, Raja Bell, Shawn Marion, Steve Nash)
3                                 (Ben Gordon, Ben Wallace, Kirk Hinrich, Luol Deng, P.J. Brown)
..                                                                                           ...
261               (Dewayne Dedmon, Elfrid Payton, Nikola Vucevic, Tobias Harris, Victor Oladipo)
257                    (Andrew Wiggins, Corey Brewer, Gorgui Dieng, Thaddeus Young, Zach LaVine)
259               (Andrea Bargnani, Lance Thomas, Langston Galloway, Lou Amundson, Shane Larkin)
244                (Al Jefferson, Cody Zeller, Gerald Henderson, Kemba Walker, Lance Stephenson)
262  (K.J. McDaniels, Luc Mbah a Moute, Michael Carter-Williams, Nerlens Noel, Robert Covington)

     games_count  avg_outcome
16            26    -0.076923
5             23     0.304348
20            23     0.217391
22            22     0.363636
3             20     0.400000
..           ...          ...
261            7    -0.142857
257            6    -0.666667
259            6    -0.666667
244            5    -0.600000
262            4     0.000000

[270 rows x 5 columns]

In [78]:
most_common_starting_lineups.sort_values('season', ascending=True)

,season,home_team,home_lineup,games_count,avg_outcome
16,2007,MIN,"(Kevin Garnett, Mark Blount, Mike James, Ricky Davis, Trenton Hassell)",26,-0.076923
5,2007,DAL,"(Devin Harris, Dirk Nowitzki, Erick Dampier, Jason Terry, Josh Howard)",23,0.304348
20,2007,ORL,"(Dwight Howard, Grant Hill, Hedo Turkoglu, Jameer Nelson, Tony Battie)",23,0.217391
22,2007,PHO,"(Amar'e Stoudemire, Boris Diaw, Raja Bell, Shawn Marion, Steve Nash)",22,0.363636
3,2007,CHI,"(Ben Gordon, Ben Wallace, Kirk Hinrich, Luol Deng, P.J. Brown)",20,0.400000
...,...,...,...,...,...
264,2015,POR,"(Damian Lillard, LaMarcus Aldridge, Nicolas Batum, Robin Lopez, Wesley Matthews)",16,-0.250000
266,2015,SAS,"(Danny Green, Kawhi Leonard, Tiago Splitter, Tim Duncan, Tony Parker)",15,0.866667
265,2015,SAC,"(Ben McLemore, Darren Collison, DeMarcus Cousins, Jason Thompson, Rudy Gay)",15,0.200000
241,2015,BOS,"(Avery Bradley, Brandon Bass, Evan Turner, Marcus Smart, Tyler Zeller)",14,0.428571
247,2015,DEN,"(Arron Afflalo, Kenneth Faried, Timofey Mozgov, Ty Lawson, Wilson Chandler)",14,0.000000

In [102]:
# Group by season, home_team, and home_lineup to calculate the number of games and average outcome
team_lineup_success = df_filtered.groupby(['season', 'home_team', 'home_lineup']).agg(
    games=('game', 'count'),
    avg_outcome=('outcome', 'mean')
).reset_index()

# Optionally, filter out lineups with very few appearances to avoid outliers
min_games = 5  # Adjust threshold as needed
team_lineup_success = team_lineup_success[team_lineup_success['games'] >= min_games]

# For each season and home_team, select the lineup with the highest average outcome
idx = team_lineup_success.groupby(['season', 'home_team'])['avg_outcome'].idxmax()
most_successful_lineups = team_lineup_success.loc[idx].reset_index(drop=True)

# Sort results for easier reading (by season and success rate)
most_successful_lineups = most_successful_lineups.sort_values(['season', 'avg_outcome'], ascending=[True, False])

# Display the final DataFrame
print(most_successful_lineups)

     season home_team  \
12     2007       LAL
24     2007       SAC
3      2007       CHI
27     2007       TOR
1      2007       BOS
..      ...       ...
253    2015       LAL
252    2015       LAC
268    2015       UTA
259    2015       NYK
265    2015       SAC

                                                                    home_lineup  \
12    (Kobe Bryant, Lamar Odom, Ronny Turiaf, Sasha Vujacic, Shammond Williams)
24    (Brad Miller, Corliss Williamson, John Salmons, Kevin Martin, Mike Bibby)
3           (Adrian Griffin, Ben Wallace, Chris Duhon, Kirk Hinrich, Luol Deng)
27   (Chris Bosh, Joey Graham, Jorge Garbajosa, Jose Calderon, Morris Peterson)
1       (Allan Ray, Gerald Green, Kevinn Pinkney, Leon Powe, Sebastian Telfair)
..                                                                          ...
253            (Ed Davis, Jeremy Lin, Jordan Hill, Kobe Bryant, Wesley Johnson)
252          (Chris Paul, DeAndre Jordan, Glen Davis, J.J. Redick, Matt Barnes)
268        (Dante Exum, Elijah Millsap, Rudy Gobert, Trevor Booker, Trey Burke)
259        (Alexey Shved, Cole Aldrich, Jason Smith, Shane Larkin, Travis Wear)
265   (Andre Miller, Derrick Williams, Nik Stauskas, Omri Casspi, Reggie Evans)

     games  avg_outcome
12       5     1.000000
24       5     1.000000
3        7     0.714286
27       7     0.714286
1        6     0.666667
..     ...          ...
253     12     0.500000
252      7     0.428571
268     10     0.400000
259      6     0.333333
265      6     0.333333

[270 rows x 5 columns]

In [103]:
pd.set_option('display.max_colwidth', None)
most_successful_lineups

,season,home_team,home_lineup,games,avg_outcome
12,2007,LAL,"(Kobe Bryant, Lamar Odom, Ronny Turiaf, Sasha Vujacic, Shammond Williams)",5,1.000000
24,2007,SAC,"(Brad Miller, Corliss Williamson, John Salmons, Kevin Martin, Mike Bibby)",5,1.000000
3,2007,CHI,"(Adrian Griffin, Ben Wallace, Chris Duhon, Kirk Hinrich, Luol Deng)",7,0.714286
27,2007,TOR,"(Chris Bosh, Joey Graham, Jorge Garbajosa, Jose Calderon, Morris Peterson)",7,0.714286
1,2007,BOS,"(Allan Ray, Gerald Green, Kevinn Pinkney, Leon Powe, Sebastian Telfair)",6,0.666667
...,...,...,...,...,...
253,2015,LAL,"(Ed Davis, Jeremy Lin, Jordan Hill, Kobe Bryant, Wesley Johnson)",12,0.500000
252,2015,LAC,"(Chris Paul, DeAndre Jordan, Glen Davis, J.J. Redick, Matt Barnes)",7,0.428571
268,2015,UTA,"(Dante Exum, Elijah Millsap, Rudy Gobert, Trevor Booker, Trey Burke)",10,0.400000
259,2015,NYK,"(Alexey Shved, Cole Aldrich, Jason Smith, Shane Larkin, Travis Wear)",6,0.333333
265,2015,SAC,"(Andre Miller, Derrick Williams, Nik Stauskas, Omri Casspi, Reggie Evans)",6,0.333333

In [104]:
# Extract home players, including season information, and rename the team column
home_players = df_filtered.melt(
    id_vars=['game', 'season', 'home_team'],
    value_vars=['home_0', 'home_1', 'home_2', 'home_3', 'home_4'],
    var_name='position',
    value_name='player'
).rename(columns={'home_team': 'team'})

# Extract away players, including season information, and rename the team column
away_players = df_filtered.melt(
    id_vars=['game', 'season', 'away_team'],
    value_vars=['away_0', 'away_1', 'away_2', 'away_3', 'away_4'],
    var_name='position',
    value_name='player'
).rename(columns={'away_team': 'team'})

# Combine home and away players into one DataFrame
all_players = pd.concat(
    [home_players[['game', 'season', 'team', 'player']], 
     away_players[['game', 'season', 'team', 'player']]],
    ignore_index=True
)

# Group by team and season to get unique players for each team in each season
team_players = all_players.groupby(['team', 'season'])['player'].unique().reset_index()

# Optionally, convert the array of players to a sorted, comma-separated string for easier reading
team_players['players'] = team_players['player'].apply(lambda x: ', '.join(sorted(x)))
team_players = team_players[['team', 'season', 'players']]

team_players

,team,season,players
0,ATL,2007,"Anthony Johnson, Cedric Bozeman, Dijon Thompson, Esteban Batista, Jeremy Richardson, Joe Johnson, Josh Childress, Josh Smith, Lorenzen Wright, Marvin Williams, Matt Freije, Royal Ivey, Salim Stoudamire, Shelden Williams, Solomon Jones, Speedy Claxton, Stanislav Medvedenko, Tyronn Lue, Zaza Pachulia"
1,ATL,2008,"Acie Law, Al Horford, Anthony Johnson, Jeremy Richardson, Joe Johnson, Josh Childress, Josh Smith, Lorenzen Wright, Mario West, Marvin Williams, Mike Bibby, Salim Stoudamire, Shelden Williams, Solomon Jones, Tyronn Lue, Zaza Pachulia"
2,ATL,2009,"Acie Law, Al Horford, Joe Johnson, Josh Smith, Mario West, Marvin Williams, Maurice Evans, Mike Bibby, Othello Hunter, Randolph Morris, Ronald Murray, Solomon Jones, Speedy Claxton, Thomas Gardner, Zaza Pachulia"
3,ATL,2010,"Al Horford, Jamal Crawford, Jason Collins, Jeff Teague, Joe Johnson, Joe Smith, Josh Smith, Mario West, Marvin Williams, Maurice Evans, Mike Bibby, Othello Hunter, Randolph Morris, Zaza Pachulia"
4,ATL,2011,"Al Horford, Damien Wilkins, Etan Thomas, Hilton Armstrong, Jamal Crawford, Jason Collins, Jeff Teague, Joe Johnson, Jordan Crawford, Josh Powell, Josh Smith, Kirk Hinrich, Marvin Williams, Maurice Evans, Mike Bibby, Pape Sy, Zaza Pachulia"
...,...,...,...
265,WAS,2011,"Al Thornton, Alonzo Gee, Andray Blatche, Cartier Martin, Gilbert Arenas, Hamady N'Diaye, Hilton Armstrong, JaVale McGee, John Wall, Jordan Crawford, Josh Howard, Kevin Seraphin, Kirk Hinrich, Larry Owens, Lester Hudson, Maurice Evans, Mike Bibby, Mustafa Shakur, Nick Young, Othyus Jeffers, Rashard Lewis, Trevor Booker, Yi Jianlian"
266,WAS,2012,"Andray Blatche, Brian Cook, Cartier Martin, Chris Singleton, Edwin Ubiles, JaVale McGee, James Singleton, Jan Vesely, John Wall, Jordan Crawford, Kevin Seraphin, Maurice Evans, Morris Almond, Nene Hilario, Nick Young, Rashard Lewis, Roger Mason, Ronny Turiaf, Shelvin Mack, Trevor Booker"
267,WAS,2013,"A.J. Price, Bradley Beal, Cartier Martin, Chris Singleton, Earl Barron, Emeka Okafor, Garrett Temple, Jan Vesely, Jannero Pargo, Jason Collins, John Wall, Jordan Crawford, Kevin Seraphin, Martell Webster, Nene Hilario, Shaun Livingston, Shelvin Mack, Trevor Ariza, Trevor Booker"
268,WAS,2014,"Al Harrington, Andre Miller, Bradley Beal, Chris Singleton, Drew Gooden, Eric Maynor, Garrett Temple, Glen Rice, Jan Vesely, John Wall, Kevin Seraphin, Marcin Gortat, Martell Webster, Nene Hilario, Otto Porter, Trevor Ariza, Trevor Booker"
269,WAS,2015,"Andre Miller, Bradley Beal, DeJuan Blair, Drew Gooden, Garrett Temple, Glen Rice, John Wall, Kevin Seraphin, Kris Humphries, Marcin Gortat, Martell Webster, Nene Hilario, Otto Porter, Paul Pierce, Ramon Sessions, Rasual Butler, Toure' Murry, Will Bynum"

In [115]:
# Melt the home player columns to analyze player participation
home_players = df_filtered.melt(
    id_vars=['game', 'season', 'home_team'],
    value_vars=['home_0', 'home_1', 'home_2', 'home_3', 'home_4'],
    var_name='home_position',
    value_name='player'
).rename(columns={'home_team': 'team'})

# Melt the away player columns
away_players = df_filtered.melt(
    id_vars=['game', 'season', 'away_team'],
    value_vars=['away_0', 'away_1', 'away_2', 'away_3', 'away_4'],
    var_name='away_position',
    value_name='player'
).rename(columns={'away_team': 'team'})

# Combine both home and away players into one DataFrame
all_players = pd.concat(
    [home_players[['game', 'season', 'team', 'player']], 
     away_players[['game', 'season', 'team', 'player']]],
    ignore_index=True
)

# Count how many games each player appeared in for each team in each season
player_game_counts = all_players.groupby(['season', 'team', 'player'])['game'].nunique().reset_index()

# Rename the column for clarity
player_game_counts.rename(columns={'game': 'games_played'}, inplace=True)

# Sort the results for better readability
player_game_counts = player_game_counts.sort_values(['season', 'team', 'games_played'], ascending=[True, True, False])


player_game_counts

      season team            player  games_played
13      2007  ATL  Shelden Williams            81
7       2007  ATL        Josh Smith            72
18      2007  ATL     Zaza Pachulia            72
8       2007  ATL   Lorenzen Wright            67
9       2007  ATL   Marvin Williams            64
...      ...  ...               ...           ...
4725    2015  WAS    Ramon Sessions            28
4713    2015  WAS      DeJuan Blair            26
4728    2015  WAS        Will Bynum             6
4716    2015  WAS         Glen Rice             5
4727    2015  WAS      Toure' Murry             3

[4729 rows x 4 columns]

In [105]:
# First, aggregate unique players by team and season without converting to string
team_players_df = all_players.groupby(['team', 'season'])['player'].unique().reset_index()

# Convert the 'player' column (which is an array) to a list for each row
team_players_df['player'] = team_players_df['player'].apply(list)

# Now, build a nested dictionary: {team: {season: [players]}}
rosters_dict = {}
for _, row in team_players_df.iterrows():
    team = row['team']
    season = row['season']
    players_list = row['player']
    if team not in rosters_dict:
        rosters_dict[team] = {}
    rosters_dict[team][season] = sorted(players_list)  # sorted for consistency

# Print the dictionary
print(rosters_dict)

{'ATL': {2007: ['Anthony Johnson', 'Cedric Bozeman', 'Dijon Thompson', 'Esteban Batista', 'Jeremy Richardson', 'Joe Johnson', 'Josh Childress', 'Josh Smith', 'Lorenzen Wright', 'Marvin Williams', 'Matt Freije', 'Royal Ivey', 'Salim Stoudamire', 'Shelden Williams', 'Solomon Jones', 'Speedy Claxton', 'Stanislav Medvedenko', 'Tyronn Lue', 'Zaza Pachulia'], 2008: ['Acie Law', 'Al Horford', 'Anthony Johnson', 'Jeremy Richardson', 'Joe Johnson', 'Josh Childress', 'Josh Smith', 'Lorenzen Wright', 'Mario West', 'Marvin Williams', 'Mike Bibby', 'Salim Stoudamire', 'Shelden Williams', 'Solomon Jones', 'Tyronn Lue', 'Zaza Pachulia'], 2009: ['Acie Law', 'Al Horford', 'Joe Johnson', 'Josh Smith', 'Mario West', 'Marvin Williams', 'Maurice Evans', 'Mike Bibby', 'Othello Hunter', 'Randolph Morris', 'Ronald Murray', 'Solomon Jones', 'Speedy Claxton', 'Thomas Gardner', 'Zaza Pachulia'], 2010: ['Al Horford', 'Jamal Crawford', 'Jason Collins', 'Jeff Teague', 'Joe Johnson', 'Joe Smith', 'Josh Smith', 'Mario West', 'Marvin Williams', 'Maurice Evans', 'Mike Bibby', 'Othello Hunter', 'Randolph Morris', 'Zaza Pachulia'], 2011: ['Al Horford', 'Damien Wilkins', 'Etan Thomas', 'Hilton Armstrong', 'Jamal Crawford', 'Jason Collins', 'Jeff Teague', 'Joe Johnson', 'Jordan Crawford', 'Josh Powell', 'Josh Smith', 'Kirk Hinrich', 'Marvin Williams', 'Maurice Evans', 'Mike Bibby', 'Pape Sy', 'Zaza Pachulia'], 2012: ['Al Horford', 'Donald Sloan', 'Erick Dampier', 'Ivan Johnson', 'Jannero Pargo', 'Jason Collins', 'Jeff Teague', 'Jerry Stackhouse', 'Joe Johnson', 'Josh Smith', 'Kirk Hinrich', 'Marvin Williams', 'Tracy McGrady', 'Vladimir Radmanovic', 'Willie Green', 'Zaza Pachulia'], 2013: ['Al Horford', 'Anthony Morrow', 'Anthony Tolliver', 'Dahntay Jones', 'DeShawn Stevenson', 'Devin Harris', 'Ivan Johnson', 'Jannero Pargo', 'Jeff Teague', 'Jeremy Tyler', 'Johan Petro', 'John Jenkins', 'Josh Smith', 'Kyle Korver', 'Lou Williams', 'Mike Scott', 'Shelvin Mack', 'Zaza Pachulia'], 2014: ['Al Horford', 'Cartier Martin', 'DeMarre Carroll', 'Dennis Schroder', 'Dexter Pittman', 'Elton Brand', 'Gustavo Ayon', 'James Nunnally', 'Jared Cunningham', 'Jeff Teague', 'John Jenkins', 'Kyle Korver', 'Lou Williams', 'Mike Muscala', 'Mike Scott', 'Paul Millsap', 'Pero Antic', 'Shelvin Mack'], 2015: ['Adreian Payne', 'Al Horford', 'Austin Daye', 'DeMarre Carroll', 'Dennis Schroder', 'Elton Brand', 'Jeff Teague', 'John Jenkins', 'Kent Bazemore', 'Kyle Korver', 'Mike Muscala', 'Mike Scott', 'Paul Millsap', 'Pero Antic', 'Shelvin Mack', 'Thabo Sefolosha']}, 'BOS': {2007: ['Al Jefferson', 'Allan Ray', 'Brian Scalabrine', 'Delonte West', 'Gerald Green', 'Kendrick Perkins', 'Kevinn Pinkney', 'Leon Powe', 'Michael Olowokandi', 'Paul Pierce', 'Rajon Rondo', 'Ryan Gomes', 'Sebastian Telfair', 'Theo Ratliff', 'Tony Allen', 'Wally Szczerbiak'], 2008: ['Brian Scalabrine', 'Eddie House', 'Gabe Pruitt', 'Glen Davis', 'James Posey', 'Kendrick Perkins', 'Kevin Garnett', 'Leon Powe', 'P.J. Brown', 'Paul Pierce', 'Rajon Rondo', 'Ray Allen', 'Sam Cassell', 'Scot Pollard', 'Tony Allen'], 2009: ['Brian Scalabrine', 'Eddie House', 'Gabe Pruitt', 'Glen Davis', 'Henry Walker', 'J.R. Giddens', 'Kendrick Perkins', 'Kevin Garnett', 'Leon Powe', 'Mikki Moore', "Patrick O'Bryant", 'Paul Pierce', 'Rajon Rondo', 'Ray Allen', 'Stephon Marbury', 'Tony Allen'], 2010: ['Brian Scalabrine', 'Eddie House', 'Glen Davis', 'Henry Walker', 'J.R. Giddens', 'Kendrick Perkins', 'Kevin Garnett', 'Lester Hudson', 'Marcus Landry', 'Marquis Daniels', 'Michael Finley', 'Nate Robinson', 'Oliver Lafayette', 'Paul Pierce', 'Rajon Rondo', 'Rasheed Wallace', 'Ray Allen', 'Shelden Williams', 'Tony Allen'], 2011: ['Avery Bradley', 'Carlos Arroyo', 'Chris Johnson', 'Delonte West', 'Glen Davis', 'Jeff Green', "Jermaine O'Neal", 'Kendrick Perkins', 'Kevin Garnett', 'Luke Harangody', 'Marquis Daniels', 'Nate Robinson', 'Nenad Krstic', 'Paul Pierce', 'Rajon Rondo', 'Ray Allen', 'Sasha Pavlovic', 'Semih Erden', "Shaquille O'Neal", 'Troy Murphy', 'Von Wafer'], 2012: ['Avery Bradley', 'Brandon Bass', 'Chris Wilcox', "E'Twaun Moore", 'Greg Stiemsma', 'JaJuan Johnson', "Jermaine O'Neal", 'Kevin Garnett', 'Keyon Dooling', 'Marquis Daniels', 'Mickael Pietrus', 'Paul Pierce', 'Rajon Rondo', 'Ray Allen', 'Ryan Hollins', 'Sasha Pavlovic', 'Sean Williams'], 2013: ['Avery Bradley', 'Brandon Bass', 'Chris Wilcox', 'Courtney Lee', 'D.J. White', 'Darko Milicic', 'Fab Melo', 'Jared Sullinger', 'Jarvis Varnado', 'Jason Collins', 'Jason Terry', 'Jeff Green', 'Jordan Crawford', 'Kevin Garnett', 'Kris Joseph', 'Leandro Barbosa', 'Paul Pierce', 'Rajon Rondo', 'Shavlik Randolph', 'Terrence Williams'], 2014: ['Avery Bradley', 'Brandon Bass', 'Chris Babb', 'Chris Johnson', 'Courtney Lee', 'Gerald Wallace', 'Jared Sullinger', 'Jeff Green', 'Jerryd Bayless', 'Joel Anthony', 'Jordan Crawford', 'Keith Bogans', 'Kelly Olynyk', 'Kris Humphries', 'MarShon Brooks', 'Phil Pressey', 'Rajon Rondo', 'Vander Blue', 'Vitor Faverani'], 2015: ['Avery Bradley', 'Brandan Wright', 'Brandon Bass', 'Dwight Powell', 'Evan Turner', 'Gerald Wallace', 'Isaiah Thomas', 'Jae Crowder', 'Jameer Nelson', 'James Young', 'Jared Sullinger', 'Jeff Green', 'Jonas Jerebko', 'Kelly Olynyk', 'Luigi Datome', 'Marcus Smart', 'Marcus Thornton', 'Phil Pressey', 'Rajon Rondo', 'Shavlik Randolph', 'Tayshaun Prince', 'Tyler Zeller']}, 'BRK': {2013: ['Andray Blatche', 'Brook Lopez', 'C.J. Watson', 'Deron Williams', 'Gerald Wallace', 'Jerry Stackhouse', 'Joe Johnson', 'Josh Childress', 'Keith Bogans', 'Kris Humphries', 'Kris Joseph', 'MarShon Brooks', 'Mirza Teletovic', 'Reggie Evans', 'Tornike Shengelia', 'Tyshawn Taylor'], 2014: ['Alan Anderson', 'Andray Blatche', 'Andrei Kirilenko', 'Brook Lopez', 'Deron Williams', 'Jason Collins', 'Jason Terry', 'Joe Johnson', 'Jorge Gutierrez', 'Kevin Garnett', 'Marcus Thornton', 'Marquis Teague', 'Mason Plumlee', 'Mirza Teletovic', 'Paul Pierce', 'Reggie Evans', 'Shaun Livingston', 'Tornike Shengelia', 'Tyshawn Taylor'], 2015: ['Alan Anderson', 'Andrei Kirilenko', 'Bojan Bogdanovic', 'Brandon Davies', 'Brook Lopez', 'Cory Jefferson', 'Darius Morris', 'Deron Williams', 'Earl Clark', 'Jarrett Jack', 'Jerome Jordan', 'Joe Johnson', 'Jorge Gutierrez', 'Kevin Garnett', 'Markel Brown', 'Mason Plumlee', 'Mirza Teletovic', 'Sergey Karasev', 'Thaddeus Young']}, 'CHA': {2007: ['Adam Morrison', 'Alan Anderson', 'Bernard Robinson', 'Brevin Knight', 'Derek Anderson', 'Emeka Okafor', 'Eric Williams', 'Gerald Wallace', 'Jake Voskuhl', 'Jeff McInnis', 'Matt Carroll', 'Melvin Ely', 'Othella Harrington', 'Primoz Brezec', 'Raymond Felton', 'Ryan Hollins', 'Sean May', 'Walter Herrmann'], 2008: ['Derek Anderson', 'Earl Boykins', 'Emeka Okafor', 'Gerald Wallace', 'Jared Dudley', 'Jason Richardson', 'Jeff McInnis', 'Jermareo Davidson', 'Matt Carroll', 'Nazr Mohammed', 'Othella Harrington', 'Primoz Brezec', 'Raymond Felton', 'Ryan Hollins', 'Walter Herrmann'], 2009: ['Adam Morrison', 'Alexis Ajinca', 'Andre Brown', 'Boris Diaw', 'Cartier Martin', 'D.J. Augustin', 'DeSagana Diop', 'Dontell Jefferson', 'Dwayne Jones', 'Emeka Okafor', 'Gerald Wallace', 'Jared Dudley', 'Jason Richardson', 'Juwan Howard', 'Linton Johnson', 'Matt Carroll', 'Nazr Mohammed', 'Raja Bell', 'Raymond Felton', 'Ryan Hollins', 'Sean May', 'Sean Singletary', 'Shannon Brown', 'Vladimir Radmanovic'], 2010: ['Acie Law', 'Alexis Ajinca', 'Boris Diaw', 'D.J. Augustin', 'DeSagana Diop', 'Derrick Brown', 'Gerald Henderson', 'Gerald Wallace', 'Larry Hughes', 'Nazr Mohammed', 'Raja Bell', 'Raymond Felton', 'Ronald Murray', 'Stephen Graham', 'Stephen Jackson', 'Theo Ratliff', 'Tyrus Thomas', 'Tyson Chandler', 'Vladimir Radmanovic'], 2011: ['Boris Diaw', 'D.J. Augustin', 'D.J. White', 'Dante Cunningham', 'DeSagana Diop', 'Derrick Brown', 'Dominic McGuire', 'Eduardo Najera', 'Garrett Temple', 'Gerald Henderson', 'Gerald Wallace', 'Joel Przybilla', 'Kwame Brown', 'Matt Carroll', 'Nazr Mohammed', 'Shaun Livingston', 'Sherron Collins', 'Stephen Jackson', 'Tyrus Thomas'], 2012: ['Bismack Biyombo', 'Boris Diaw', 'Byron Mullens', 'Corey Maggette', 'Cory Higgins', 'D.J. Augustin', 'D.J. White', 'DeSagana Diop', 'Derrick Brown', 'Eduardo Najera', 'Gerald Henderson', 'Jamario Moon', 'Kemba Walker', 'Matt Carroll', 'Reggie Williams', 'Tyrus Thomas'], 2013: ['Ben Gordon', 'Bismack Biyombo', 'Brendan Haywood', 'Byron Mullens', 'Cory Higgins', 'DeSagana Diop', 'Gerald Henderson', 'Hakim Warrick', 'Jannero Pargo', 'Jeff Adrien', 'Jeffery Taylor', 'Josh McRoberts', 'Kemba Walker', 'Matt Carroll', 'Michael Kidd-Gilchrist', 'Ramon Sessions', 'Reggie Williams', 'Tyrus Thomas'], 2014: ['Al Jefferson', 'Anthony Tolliver', 'Ben Gordon', 'Bismack Biyombo', 'Chris Douglas-Roberts', 'Cody Zeller', 'D.J. White', 'Gary Neal', 'Gerald Henderson', 'James Southerland', 'Jannero Pargo', 'Jeff Adrien', 'Jeffery Taylor', 'Josh McRoberts', 'Justin Hamilton', 'Kemba Walker', 'Luke Ridnour', 'Michael Kidd-Gilchrist', 'Ramon Sessions']}, 'CHI': {2007: ['Adrian Griffin', 'Andre Barrett', 'Andres Nocioni', 'Ben Gordon', 'Ben Wallace', 'Chris Duhon', 'Kirk Hinrich', 'Luol Deng', 'Malik Allen', 'Mike Sweetney', 'P.J. Brown', 'Thabo Sefolosha', 'Tyrus Thomas', 'Viktor Khryapa'], 2008: ['Aaron Gray', 'Adrian Griffin', 'Andres Nocioni', 'Ben Gordon', 'Ben Wallace', 'Cedric Simmons', 'Chris Duhon', 'Demetris Nichols', 'Drew Gooden', 'Joakim Noah', 'Joe Smith', 'Kirk Hinrich', 'Larry Hughes', 'Luol Deng', 'Shannon Brown', 'Thabo Sefolosha', 'Thomas Gardner', 'Tyrus Thomas', 'Viktor Khryapa'], 2009: ['Aaron Gray', 'Andres Nocioni', 'Anthony Roberson', 'Ben Gordon', 'Brad Miller', 'Cedric Simmons', 'Demetris Nichols', 'Derrick Rose', 'Drew Gooden', 'Joakim Noah', 'John Salmons', 'Kirk Hinrich', 'Larry Hughes', 'Lindsey Hunter', 'Linton Johnson', 'Luol Deng', 'Thabo Sefolosha', 'Tim Thomas', 'Tyrus Thomas'], 2010: ['Aaron Gray', 'Acie Law', 'Brad Miller', 'Chris Richard', 'Derrick Rose', 'Devin Brown', 'Hakim Warrick', 'James Johnson', 'Jannero Pargo', 'Joakim Noah', 'Joe Alexander', 'John Salmons', 'Kirk Hinrich', 'Lindsey Hunter', 'Luol Deng', 'Ronald Murray', 'Taj Gibson', 'Tyrus Thomas'], 2011: ['Brian Scalabrine', 'C.J. Watson', 'Carlos Boozer', 'Derrick Rose', 'James Johnson', 'Joakim Noah', 'John Lucas III', 'Keith Bogans', 'Kurt Thomas', 'Kyle Korver', 'Luol Deng', 'Omer Asik', 'Rasual Butler', 'Ronnie Brewer', 'Taj Gibson'], 2012: ['Brian Scalabrine', 'C.J. Watson', 'Carlos Boozer', 'Derrick Rose', 'Jimmy Butler', 'Joakim Noah', 'John Lucas III', 'Kyle Korver', 'Luol Deng', 'Mike James', 'Omer Asik', 'Richard Hamilton', 'Ronnie Brewer', 'Taj Gibson'], 2013: ['Carlos Boozer', 'Daequan Cook', 'Jimmy Butler', 'Joakim Noah', 'Kirk Hinrich', 'Luol Deng', 'Malcolm Thomas', 'Marco Belinelli', 'Marquis Teague', 'Nate Robinson', 'Nazr Mohammed', 'Richard Hamilton', 'Taj Gibson', 'Vladimir Radmanovic'], 2014: ['Carlos Boozer', 'Cartier Martin', 'D.J. Augustin', 'Derrick Rose', 'Erik Murphy', 'Jimmer Fredette', 'Jimmy Butler', 'Joakim Noah', 'Kirk Hinrich', 'Luol Deng', 'Marquis Teague', 'Mike Dunleavy', 'Mike James', 'Nazr Mohammed', 'Ronnie Brewer', 'Taj Gibson', 'Tony Snell', 'Tornike Shengelia'], 2015: ['Aaron Brooks', 'Cameron Bairstow', 'Derrick Rose', 'Doug McDermott', "E'Twaun Moore", 'Jimmy Butler', 'Joakim Noah', 'Kirk Hinrich', 'Mike Dunleavy', 'Nazr Mohammed', 'Nikola Mirotic', 'Pau Gasol', 'Taj Gibson', 'Tony Snell']}, 'CHO': {2015: ['Al Jefferson', 'Bismack Biyombo', 'Brian Roberts', 'Cody Zeller', 'Gary Neal', 'Gerald Henderson', 'Jannero Pargo', 'Jason Maxiell', 'Jeffery Taylor', 'Kemba Walker', 'Lance Stephenson', 'Marvin Williams', 'Michael Kidd-Gilchrist', 'Mo Williams', 'Noah Vonleh', 'P.J. Hairston', 'Troy Daniels']}, 'CLE': {2007: ['Anderson Varejao', 'Damon Jones', 'Daniel Gibson', 'David Wesley', 'Donyell Marshall', 'Drew Gooden', 'Dwayne Jones', 'Eric Snow', 'Ira Newble', 'Larry Hughes', 'LeBron James', 'Sasha Pavlovic', 'Scot Pollard', 'Shannon Brown', 'Zydrunas Ilgauskas'], 2008: ['Anderson Varejao', 'Ben Wallace', 'Billy Thomas', 'Cedric Simmons', 'Damon Jones', 'Daniel Gibson', 'Delonte West', 'Demetris Nichols', 'Devin Brown', 'Donyell Marshall', 'Drew Gooden', 'Dwayne Jones', 'Eric Snow', 'Ira Newble', 'Joe Smith', 'Kaniel Dickens', 'Lance Allred', 'Larry Hughes', 'LeBron James', 'Sasha Pavlovic', 'Shannon Brown', 'Wally Szczerbiak', 'Zydrunas Ilgauskas'], 2009: ['Anderson Varejao', 'Ben Wallace', 'Daniel Gibson', 'Darnell Jackson', 'Delonte West', 'J.J. Hickson', 'Jawad Williams', 'Joe Smith', 'LeBron James', 'Lorenzen Wright', 'Mo Williams', 'Sasha Pavlovic', 'Tarence Kinsey', 'Trey Johnson', 'Wally Szczerbiak', 'Zydrunas Ilgauskas'], 2010: ['Anderson Varejao', 'Antawn Jamison', 'Anthony Parker', 'Cedric Jackson', 'Coby Karl', 'Daniel Gibson', 'Danny Green', 'Darnell Jackson', 'Delonte West', 'J.J. Hickson', 'Jamario Moon', 'Jawad Williams', 'LeBron James', 'Leon Powe', 'Mo Williams', 'Sebastian Telfair', "Shaquille O'Neal", 'Zydrunas Ilgauskas'], 2011: ['Alonzo Gee', 'Anderson Varejao', 'Antawn Jamison', 'Anthony Parker', 'Baron Davis', 'Christian Eyenga', 'Daniel Gibson', 'J.J. Hickson', 'Jamario Moon', 'Jawad Williams', 'Joey Graham', 'Leon Powe', 'Luke Harangody', 'Manny Harris', 'Mo Williams', 'Ramon Sessions', 'Ryan Hollins', 'Samardo Samuels', 'Semih Erden'], 2012: ['Alonzo Gee', 'Anderson Varejao', 'Antawn Jamison', 'Anthony Parker', 'Ben Uzoh', 'Christian Eyenga', 'D.J. Kennedy', 'Daniel Gibson', 'Donald Sloan', 'Kyrie Irving', 'Lester Hudson', 'Luke Harangody', 'Luke Walton', 'Manny Harris', 'Mychel Thompson', 'Omri Casspi', 'Ramon Sessions', 'Ryan Hollins', 'Samardo Samuels', 'Semih Erden', 'Tristan Thompson'], 2013: ['Alonzo Gee', 'Anderson Varejao', 'C.J. Miles', 'Chris Quinn', 'Daniel Gibson', 'Dion Waiters', 'Donald Sloan', 'Jeremy Pargo', 'Jon Leuer', 'Kevin Jones', 'Kyrie Irving', 'Luke Walton', 'Marreese Speights', 'Omri Casspi', 'Samardo Samuels', 'Shaun Livingston', 'Tristan Thompson', 'Tyler Zeller', 'Wayne Ellington'], 2014: ['Alonzo Gee', 'Anderson Varejao', 'Andrew Bynum', 'Anthony Bennett', 'Arinze Onuaku', 'C.J. Miles', 'Carrick Felix', 'Dion Waiters', 'Earl Clark', 'Henry Sims', 'Jarrett Jack', 'Kyrie Irving', 'Luol Deng', 'Matthew Dellavedova', 'Scotty Hopson', 'Sergey Karasev', 'Seth Curry', 'Shane Edwards', 'Spencer Hawes', 'Tristan Thompson', 'Tyler Zeller'], 2015: ['A.J. Price', 'Alex Kirk', 'Anderson Varejao', 'Brendan Haywood', 'Dion Waiters', 'Iman Shumpert', 'J.R. Smith', 'James Jones', 'Joe Harris', 'Kendrick Perkins', 'Kevin Love', 'Kyrie Irving', 'LeBron James', 'Lou Amundson', 'Matthew Dellavedova', 'Mike Miller', 'Shawn Marion', 'Timofey Mozgov', 'Tristan Thompson', 'Will Cherry']}, 'DAL': {2007: ['Anthony Johnson', 'Austin Croshere', 'DeSagana Diop', 'Devean George', 'Devin Harris', 'Didier Ilunga-Mbenga', 'Dirk Nowitzki', 'Erick Dampier', 'Greg Buckner', 'J.J. Barea', 'Jason Terry', 'Jerry Stackhouse', 'Josh Howard', 'Kevin Willis', 'Maurice Ager', 'Pops Mensah-Bonsu'], 2008: ['Antoine Wright', 'Brandon Bass', 'DeSagana Diop', 'Devean George', 'Devin Harris', 'Dirk Nowitzki', 'Eddie Jones', 'Erick Dampier', 'J.J. Barea', 'Jamaal Magloire', 'Jason Kidd', 'Jason Terry', 'Jerry Stackhouse', 'Josh Howard', 'Juwan Howard', 'Malik Allen', 'Maurice Ager', 'Nick Fazekas', 'Trenton Hassell', 'Tyronn Lue'], 2009: ['Antoine Wright', 'Brandon Bass', 'DeSagana Diop', 'Devean George', 'Dirk Nowitzki', 'Erick Dampier', 'Gerald Green', 'J.J. Barea', 'James Singleton', 'Jason Kidd', 'Jason Terry', 'Jerry Stackhouse', 'Josh Howard', 'Matt Carroll', 'Ryan Hollins', 'Shawne Williams'], 2010: ['Brendan Haywood', 'Caron Butler', 'DeShawn Stevenson', 'Dirk Nowitzki', 'Drew Gooden', 'Eduardo Najera', 'Erick Dampier', 'J.J. Barea', 'James Singleton', 'Jason Kidd', 'Jason Terry', 'Josh Howard', 'Kris Humphries', 'Matt Carroll', 'Quinton Ross', 'Rodrigue Beaubois', 'Shawn Marion', 'Tim Thomas'], 2011: ['Alexis Ajinca', 'Brendan Haywood', 'Brian Cardinal', 'Caron Butler', 'Corey Brewer', 'DeShawn Stevenson', 'Dirk Nowitzki', 'Dominique Jones', 'Ian Mahinmi', 'J.J. Barea', 'Jason Kidd', 'Jason Terry', 'Peja Stojakovic', 'Rodrigue Beaubois', 'Sasha Pavlovic', 'Shawn Marion', 'Steve Novak', 'Tyson Chandler'], 2012: ['Brandan Wright', 'Brendan Haywood', 'Brian Cardinal', 'Delonte West', 'Dirk Nowitzki', 'Dominique Jones', 'Ian Mahinmi', 'Jason Kidd', 'Jason Terry', 'Kelenna Azubuike', 'Lamar Odom', 'Rodrigue Beaubois', 'Sean Williams', 'Shawn Marion', 'Vince Carter', 'Yi Jianlian'], 2013: ['Anthony Morrow', 'Bernard James', 'Brandan Wright', 'Chris Douglas-Roberts', 'Chris Kaman', 'Chris Wright', 'Dahntay Jones', 'Darren Collison', 'Derek Fisher', 'Dirk Nowitzki', 'Dominique Jones', 'Eddy Curry', 'Elton Brand', 'Jae Crowder', 'Jared Cunningham', 'Josh Akognon', 'Justin Dentmon', 'Mike James', 'O.J. Mayo', 'Rodrigue Beaubois', 'Shawn Marion', 'Troy Murphy', 'Vince Carter'], 2014: ['Bernard James', 'Brandan Wright', 'DeJuan Blair', 'Devin Harris', 'Dirk Nowitzki', 'Gal Mekel', 'Jae Crowder', 'Jose Calderon', 'Monta Ellis', 'Ricky Ledo', 'Samuel Dalembert', 'Shane Larkin', 'Shawn Marion', 'Vince Carter', 'Wayne Ellington'], 2015: ['Al-Farouq Aminu', "Amar'e Stoudemire", 'Bernard James', 'Brandan Wright', 'Chandler Parsons', 'Charlie Villanueva', 'Devin Harris', 'Dirk Nowitzki', 'Dwight Powell', 'Greg Smith', 'J.J. Barea', 'Jae Crowder', 'Jameer Nelson', 'Monta Ellis', 'Rajon Rondo', 'Raymond Felton', 'Richard Jefferson', 'Ricky Ledo', 'Tyson Chandler']}, 'DEN': {2007: ['Allen Iverson', 'Andre Miller', 'Anthony Carter', 'Carmelo Anthony', 'DerMarr Johnson', 'Earl Boykins', 'Eduardo Najera', 'J.R. Smith', 'Jamal Sampson', 'Joe Smith', 'Julius Hodge', 'Kenyon Martin', 'Linas Kleiza', 'Marcus Camby', 'Nene Hilario', 'Reggie Evans', 'Steve Blake', 'Yakhouba Diawara'], 2008: ['Allen Iverson', 'Anthony Carter', 'Bobby Jones', 'Carmelo Anthony', 'Chucky Atkins', 'Eduardo Najera', 'J.R. Smith', 'Jelani McCoy', 'Kenyon Martin', 'Linas Kleiza', 'Marcus Camby', 'Mike Wilks', 'Nene Hilario', 'Steven Hunter', 'Taurean Green', 'Von Wafer', 'Yakhouba Diawara'], 2009: ['Allen Iverson', 'Anthony Carter', 'Carmelo Anthony', 'Chauncey Billups', 'Cheikh Samb', 'Chris Andersen', 'Chucky Atkins', 'Dahntay Jones', 'J.R. Smith', 'Jason Hart', 'Johan Petro', 'Juwan Howard', 'Kenyon Martin', 'Linas Kleiza', 'Nene Hilario', 'Renaldo Balkman', 'Sonny Weems'], 2010: ['Anthony Carter', 'Arron Afflalo', 'Carmelo Anthony', 'Chauncey Billups', 'Chris Andersen', 'J.R. Smith', 'Joey Graham', 'Johan Petro', 'Kenyon Martin', 'Malik Allen', 'Nene Hilario', 'Renaldo Balkman', 'Ty Lawson'], 2011: ['Al Harrington', 'Anthony Carter', 'Arron Afflalo', 'Carmelo Anthony', 'Chauncey Billups', 'Chris Andersen', 'Danilo Gallinari', 'Gary Forbes', 'J.R. Smith', 'Kenyon Martin', 'Kosta Koufos', 'Melvin Ely', 'Nene Hilario', 'Raymond Felton', 'Renaldo Balkman', 'Shelden Williams', 'Timofey Mozgov', 'Ty Lawson', 'Wilson Chandler'], 2012: ['Al Harrington', 'Andre Miller', 'Arron Afflalo', 'Chris Andersen', 'Corey Brewer', 'Danilo Gallinari', 'DeMarre Carroll', 'JaVale McGee', 'Jordan Hamilton', 'Julyan Stone', 'Kenneth Faried', 'Kosta Koufos', 'Nene Hilario', 'Rudy Fernandez', 'Timofey Mozgov', 'Ty Lawson', 'Wilson Chandler'], 2013: ['Andre Iguodala', 'Andre Miller', 'Anthony Randolph', 'Corey Brewer', 'Danilo Gallinari', 'Evan Fournier', 'JaVale McGee', 'Jordan Hamilton', 'Julyan Stone', 'Kenneth Faried', 'Kosta Koufos', 'Quincy Miller', 'Timofey Mozgov', 'Ty Lawson', 'Wilson Chandler'], 2014: ['Aaron Brooks', 'Andre Miller', 'Anthony Randolph', 'Darrell Arthur', 'Evan Fournier', 'J.J. Hickson', 'JaVale McGee', 'Jan Vesely', 'Jordan Hamilton', 'Kenneth Faried', 'Nate Robinson', 'Quincy Miller', 'Randy Foye', 'Timofey Mozgov', 'Ty Lawson', 'Wilson Chandler'], 2015: ['Alonzo Gee', 'Arron Afflalo', 'Danilo Gallinari', 'Darrell Arthur', 'Erick Green', 'Gary Harris', 'Ian Clark', 'J.J. Hickson', 'JaVale McGee', 'Jamaal Franklin', 'Jameer Nelson', 'Joffrey Lauvergne', 'Jusuf Nurkic', 'Kenneth F

In [116]:
rosters_dict['TOR'][2015]

['Amir Johnson',
 'Bruno Caboclo',
 'Chuck Hayes',
 'DeMar DeRozan',
 'Greg Stiemsma',
 'Greivis Vasquez',
 'James Johnson',
 'Jonas Valanciunas',
 'Kyle Lowry',
 'Landry Fields',
 'Lou Williams',
 'Lucas Nogueira',
 'Patrick Patterson',
 'Terrence Ross',
 'Tyler Hansbrough']

In [112]:
# Sort the DataFrame by game and starting_min
df_sorted = df_filtered.sort_values(['game', 'starting_min']).copy()

# Compute the duration for each lineup segment per game.
# For each game, duration = next starting_min - current starting_min.
# For the last segment in each game, duration = 48 - current starting_min.
df_sorted['duration'] = df_sorted.groupby('game')['starting_min'].transform(lambda x: x.shift(-1) - x)
df_sorted['duration'] = df_sorted['duration'].fillna(48 - df_sorted['starting_min'])

# Melt the home lineup columns so each row corresponds to a player's appearance in that lineup segment.
# Include 'season' as part of the id_vars.
home_players = df_sorted.melt(
    id_vars=['game', 'season', 'home_team', 'duration'],
    value_vars=['home_0', 'home_1', 'home_2', 'home_3', 'home_4'],
    var_name='position',
    value_name='player'
)

# Group by team, season, and player, summing the durations (which represent the minutes played)
player_minutes = home_players.groupby(['home_team', 'season', 'player'])['duration'].sum().reset_index()

# Rename the 'duration' column for clarity
player_minutes.rename(columns={'duration': 'total_minutes'}, inplace=True)

# Select the top 10 players with the most minutes played per team per season
top10_by_team_season = (
    player_minutes.sort_values(['home_team', 'season', 'total_minutes'], ascending=[True, True, False])
    .groupby(['home_team', 'season'])
    .apply(lambda x: x.nlargest(10, 'total_minutes'))
    .reset_index(drop=True)
)

In [113]:
top10_by_team_season.head(12)

   home_team  season            player  total_minutes
0        ATL    2007        Josh Smith         1322.0
1        ATL    2007       Joe Johnson         1120.0
2        ATL    2007   Marvin Williams         1107.0
3        ATL    2007    Josh Childress         1077.0
4        ATL    2007     Zaza Pachulia         1034.0
5        ATL    2007        Tyronn Lue          764.0
6        ATL    2007  Shelden Williams          720.0
7        ATL    2007   Lorenzen Wright          531.0
8        ATL    2007    Speedy Claxton          510.0
9        ATL    2007  Salim Stoudamire          488.0
10       ATL    2008       Joe Johnson         1703.0
11       ATL    2008        Josh Smith         1385.0

In [120]:
# Step 1: Extract the starting lineup for each game (i.e., the row with the smallest starting_min per game)
starting_lineups = df_filtered.sort_values('starting_min').groupby('game').first().reset_index()

# Step 2: Merge with the most common starting lineups (most_common_starting_lineups)
# most_common_starting_lineups has columns: season, home_team, home_lineup, games_count, avg_outcome
common_starting_games = starting_lineups.merge(
    most_common_starting_lineups[['season', 'home_team', 'home_lineup']],
    on=['season', 'home_team', 'home_lineup'],
    how='inner'
)

# Step 3: Now, group by season, home_team, and away_team to compute the number of games and average outcome
team_vs_team_common_lineup = common_starting_games.groupby(['season', 'home_team', 'away_team']).agg(
    games_played=('game', 'count'),
    avg_outcome=('outcome', 'mean')
).reset_index()

# Step 4: Sort the results (by season, team, then average outcome descending)
team_vs_team_common_lineup = team_vs_team_common_lineup.sort_values(
    ['season', 'home_team', 'avg_outcome'], ascending=[True, True, False]
)

In [123]:
team_vs_team_common_lineup.head(30)

    season home_team away_team  games_played  avg_outcome
0     2007       ATL       CHI             1          1.0
2     2007       ATL       MEM             1          1.0
4     2007       ATL       MIN             1          1.0
5     2007       ATL       PHI             1          1.0
6     2007       ATL       POR             1          1.0
7     2007       ATL       SAC             1          1.0
1     2007       ATL       DAL             1         -1.0
3     2007       ATL       MIA             1         -1.0
8     2007       BOS       DET             1          1.0
9     2007       BOS       IND             1          1.0
11    2007       BOS       NYK             1          1.0
10    2007       BOS       NJN             1         -1.0
12    2007       BOS       ORL             1         -1.0
13    2007       BOS       POR             1         -1.0
14    2007       CHA       CHI             1         -1.0
15    2007       CHA       NOK             1         -1.0
16    2007       CHA       POR             1         -1.0
17    2007       CHA       TOR             1         -1.0
18    2007       CHA       WAS             1         -1.0
20    2007       CHI       BOS             1          1.0
21    2007       CHI       CHA             1          1.0
22    2007       CHI       CLE             1          1.0
23    2007       CHI       DAL             1          1.0
25    2007       CHI       DET             1          1.0
26    2007       CHI       GSW             1          1.0
27    2007       CHI       IND             1          1.0
28    2007       CHI       LAC             1          1.0
29    2007       CHI       MIA             1          1.0
30    2007       CHI       MIL             1          1.0
31    2007       CHI       NYK             1          1.0

In [61]:
from sklearn.model_selection import KFold
import pandas as pd

# Define individual player columns
player_columns = ['home_0', 'home_1', 'home_2', 'home_3', 'home_4',
                  'away_0', 'away_1', 'away_2', 'away_3', 'away_4']

# Create a copy of the dataset for encoding
df_encoded = df_filtered.copy()

# Initialize dictionary to store mean outcome values per player per team per season
player_mean_outcome = {}

# Apply K-Fold Cross-Validation for Mean Encoding (Avoids Data Leakage)
kf = KFold(n_splits=5, shuffle=True, random_state=42)

for train_index, val_index in kf.split(df_encoded):
    train_data, val_data = df_encoded.iloc[train_index], df_encoded.iloc[val_index]

    for col in player_columns:
        # Compute mean outcome per player within each team and season
        player_mean = train_data.groupby(['season', 'home_team', col])['outcome'].mean()

        # Store computed values
        player_mean_outcome.update(player_mean.to_dict())

        # Apply encoding to validation set
        val_data[col] = val_data.set_index(['season', 'home_team', col]).index.map(player_mean_outcome)

    # Update the main dataset with mean encoded values
    df_encoded.iloc[val_index] = val_data

# Fill NaN values for unseen players with:
# - Team-season win rate
# - Global average outcome across all seasons
df_encoded['team_season_win_rate'] = df_encoded.groupby(['season', 'home_team'])['outcome'].transform('mean')
overall_mean_outcome = df_encoded['outcome'].mean()

for col in player_columns:
    df_encoded[col] = df_encoded[col].fillna(df_encoded['team_season_win_rate']).fillna(overall_mean_outcome)

# Display the final dataset after encoding
print("Final Dataset After Mean Encoding:")
display(df_encoded)
print(df_encoded.info())

Final Dataset After Mean Encoding:

,game,season,home_team,away_team,starting_min,home_0,home_1,home_2,home_3,home_4,away_0,away_1,away_2,away_3,away_4,outcome,date,home_lineup,away_lineup,team_season_win_rate
0,200610310LAL,2007,LAL,PHO,0,-0.183486,0.052632,-0.065217,-0.142857,-0.120000,0.555556,-0.333333,0.200000,0.100000,-0.076923,-1,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Sasha Vujacic, Smush Parker)","(Boris Diaw, Kurt Thomas, Raja Bell, Shawn Marion, Steve Nash)",-0.132723
1,200610310LAL,2007,LAL,PHO,6,-0.208333,0.192308,0.044776,-0.056604,-0.087500,0.200000,0.000000,0.333333,0.230769,0.200000,-1,2006-10-31,"(Andrew Bynum, Lamar Odom, Luke Walton, Sasha Vujacic, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",-0.132723
2,200610310LAL,2007,LAL,PHO,8,-0.083333,-0.142857,0.037037,0.314286,-0.135802,0.333333,0.000000,0.333333,0.500000,0.600000,1,2006-10-31,"(Lamar Odom, Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker)","(Amar'e Stoudemire, Leandro Barbosa, Raja Bell, Shawn Marion, Steve Nash)",-0.132723
3,200610310LAL,2007,LAL,PHO,10,0.333333,-0.076923,0.056604,0.101449,-0.087500,0.500000,0.600000,0.500000,0.500000,1.000000,1,2006-10-31,"(Lamar Odom, Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)",-0.132723
4,200610310LAL,2007,LAL,PHO,11,-0.132723,-0.384615,-0.241379,-0.296296,-0.180124,0.272727,0.166667,0.111111,0.200000,1.000000,-1,2006-10-31,"(Luke Walton, Maurice Evans, Ronny Turiaf, Smush Parker, Vladimir Radmanovic)","(Boris Diaw, James Jones, Kurt Thomas, Leandro Barbosa, Marcus Banks)",-0.132723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236907,201504050NYK,2015,NYK,PHI,35,-0.250000,-0.250000,1.000000,-0.260870,-0.312500,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1,2015-04-05,"(Jason Smith, Quincy Acy, Ricky Ledo, Shane Larkin, Tim Hardaway)","(Henry Sims, Hollis Thompson, JaKarr Sampson, Jason Richardson, Jerami Grant)",-0.209063
236908,201504050NYK,2015,NYK,PHI,39,-0.314286,-0.200000,-0.222222,-0.250000,-0.328571,0.000000,-0.714286,-1.000000,-0.500000,-1.000000,-1,2015-04-05,"(Jason Smith, Langston Galloway, Quincy Acy, Ricky Ledo, Tim Hardaway)","(Henry Sims, Hollis Thompson, JaKarr Sampson, Jason Richardson, Jerami Grant)",-0.209063
236909,201504050NYK,2015,NYK,PHI,40,-0.314286,-0.200000,-0.222222,-0.250000,-0.328571,-0.500000,-0.714286,-1.000000,-0.500000,-0.500000,-1,2015-04-05,"(Jason Smith, Langston Galloway, Quincy Acy, Ricky Ledo, Tim Hardaway)","(Furkan Aldemir, Hollis Thompson, JaKarr Sampson, Jason Richardson, Nerlens Noel)",-0.209063
236910,201504050NYK,2015,NYK,PHI,42,-0.307692,-0.202532,-0.262136,-0.182796,-0.280000,-0.400000,0.142857,-0.428571,0.181818,-0.333333,-1,2015-04-05,"(Andrea Bargnani, Jason Smith, Lance Thomas, Langston Galloway, Shane Larkin)","(Furkan Aldemir, Ish Smith, Jerami Grant, Nerlens Noel, Robert Covington)",-0.209063
236911,201504050NYK,2015,NYK,PHI,45,-0.307692,-0.202532,-0.262136,-0.182796,-0.280000,-0.400000,-0.428571,0.333333,0.181818,-0.333333,1,2015-04-05,"(Andrea Bargnani, Jason Smith, Lance Thomas, Langston Galloway, Shane Larkin)","(Furkan Aldemir, Hollis Thompson, Ish Smith, Nerlens Noel, Robert Covington)",-0.209063

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236912 entries, 0 to 236911
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   game                  236912 non-null  object
 1   season                236912 non-null  int64
 2   home_team             236912 non-null  object
 3   away_team             236912 non-null  object
 4   starting_min          236912 non-null  int64
 5   home_0                236912 non-null  float64
 6   home_1                236912 non-null  float64
 7   home_2                236912 non-null  float64
 8   home_3                236912 non-null  float64
 9   home_4                236912 non-null  float64
 10  away_0                236912 non-null  float64
 11  away_1                236912 non-null  float64
 12  away_2                236912 non-null  float64
 13  away_3                236912 non-null  float64
 14  away_4                236912 non-null  float64
 15  outcome               236912 non-null  int64
 16  date                  236912 non-null  datetime64[ns]
 17  home_lineup           236912 non-null  object
 18  away_lineup           236912 non-null  object
 19  team_season_win_rate  236912 non-null  float64
dtypes: datetime64[ns](1), float64(11), int64(3), object(5)
memory usage: 36.2+ MB
None

In [117]:
top10_by_team_season

     home_team  season           player  total_minutes
0          ATL    2007       Josh Smith         1322.0
1          ATL    2007      Joe Johnson         1120.0
2          ATL    2007  Marvin Williams         1107.0
3          ATL    2007   Josh Childress         1077.0
4          ATL    2007    Zaza Pachulia         1034.0
...        ...     ...              ...            ...
2695       WAS    2015    Rasual Butler          712.0
2696       WAS    2015   Kris Humphries          708.0
2697       WAS    2015      Otto Porter          703.0
2698       WAS    2015   Kevin Seraphin          571.0
2699       WAS    2015      Drew Gooden          412.0

[2700 rows x 4 columns]

In [70]:
team_players

,team,season,players
0,ATL,2007,"Anthony Johnson, Cedric Bozeman, Dijon Thompson, Esteban Batista, Jeremy Richardson, Joe Johnson, Josh Childress, Josh Smith, Lorenzen Wright, Marvin Williams, Matt Freije, Royal Ivey, Salim Stoudamire, Shelden Williams, Solomon Jones, Speedy Claxton, Stanislav Medvedenko, Tyronn Lue, Zaza Pachulia"
1,ATL,2008,"Acie Law, Al Horford, Anthony Johnson, Jeremy Richardson, Joe Johnson, Josh Childress, Josh Smith, Lorenzen Wright, Mario West, Marvin Williams, Mike Bibby, Salim Stoudamire, Shelden Williams, Solomon Jones, Tyronn Lue, Zaza Pachulia"
2,ATL,2009,"Acie Law, Al Horford, Joe Johnson, Josh Smith, Mario West, Marvin Williams, Maurice Evans, Mike Bibby, Othello Hunter, Randolph Morris, Ronald Murray, Solomon Jones, Speedy Claxton, Thomas Gardner, Zaza Pachulia"
3,ATL,2010,"Al Horford, Jamal Crawford, Jason Collins, Jeff Teague, Joe Johnson, Joe Smith, Josh Smith, Mario West, Marvin Williams, Maurice Evans, Mike Bibby, Othello Hunter, Randolph Morris, Zaza Pachulia"
4,ATL,2011,"Al Horford, Damien Wilkins, Etan Thomas, Hilton Armstrong, Jamal Crawford, Jason Collins, Jeff Teague, Joe Johnson, Jordan Crawford, Josh Powell, Josh Smith, Kirk Hinrich, Marvin Williams, Maurice Evans, Mike Bibby, Pape Sy, Zaza Pachulia"
...,...,...,...
265,WAS,2011,"Al Thornton, Alonzo Gee, Andray Blatche, Cartier Martin, Gilbert Arenas, Hamady N'Diaye, Hilton Armstrong, JaVale McGee, John Wall, Jordan Crawford, Josh Howard, Kevin Seraphin, Kirk Hinrich, Larry Owens, Lester Hudson, Maurice Evans, Mike Bibby, Mustafa Shakur, Nick Young, Othyus Jeffers, Rashard Lewis, Trevor Booker, Yi Jianlian"
266,WAS,2012,"Andray Blatche, Brian Cook, Cartier Martin, Chris Singleton, Edwin Ubiles, JaVale McGee, James Singleton, Jan Vesely, John Wall, Jordan Crawford, Kevin Seraphin, Maurice Evans, Morris Almond, Nene Hilario, Nick Young, Rashard Lewis, Roger Mason, Ronny Turiaf, Shelvin Mack, Trevor Booker"
267,WAS,2013,"A.J. Price, Bradley Beal, Cartier Martin, Chris Singleton, Earl Barron, Emeka Okafor, Garrett Temple, Jan Vesely, Jannero Pargo, Jason Collins, John Wall, Jordan Crawford, Kevin Seraphin, Martell Webster, Nene Hilario, Shaun Livingston, Shelvin Mack, Trevor Ariza, Trevor Booker"
268,WAS,2014,"Al Harrington, Andre Miller, Bradley Beal, Chris Singleton, Drew Gooden, Eric Maynor, Garrett Temple, Glen Rice, Jan Vesely, John Wall, Kevin Seraphin, Marcin Gortat, Martell Webster, Nene Hilario, Otto Porter, Trevor Ariza, Trevor Booker"
269,WAS,2015,"Andre Miller, Bradley Beal, DeJuan Blair, Drew Gooden, Garrett Temple, Glen Rice, John Wall, Kevin Seraphin, Kris Humphries, Marcin Gortat, Martell Webster, Nene Hilario, Otto Porter, Paul Pierce, Ramon Sessions, Rasual Butler, Toure' Murry, Will Bynum"

In [79]:
most_common_starting_lineups

,season,home_team,home_lineup,games_count,avg_outcome
16,2007,MIN,"(Kevin Garnett, Mark Blount, Mike James, Ricky Davis, Trenton Hassell)",26,-0.076923
5,2007,DAL,"(Devin Harris, Dirk Nowitzki, Erick Dampier, Jason Terry, Josh Howard)",23,0.304348
20,2007,ORL,"(Dwight Howard, Grant Hill, Hedo Turkoglu, Jameer Nelson, Tony Battie)",23,0.217391
22,2007,PHO,"(Amar'e Stoudemire, Boris Diaw, Raja Bell, Shawn Marion, Steve Nash)",22,0.363636
3,2007,CHI,"(Ben Gordon, Ben Wallace, Kirk Hinrich, Luol Deng, P.J. Brown)",20,0.400000
...,...,...,...,...,...
261,2015,ORL,"(Dewayne Dedmon, Elfrid Payton, Nikola Vucevic, Tobias Harris, Victor Oladipo)",7,-0.142857
257,2015,MIN,"(Andrew Wiggins, Corey Brewer, Gorgui Dieng, Thaddeus Young, Zach LaVine)",6,-0.666667
259,2015,NYK,"(Andrea Bargnani, Lance Thomas, Langston Galloway, Lou Amundson, Shane Larkin)",6,-0.666667
244,2015,CHO,"(Al Jefferson, Cody Zeller, Gerald Henderson, Kemba Walker, Lance Stephenson)",5,-0.600000
262,2015,PHI,"(K.J. McDaniels, Luc Mbah a Moute, Michael Carter-Williams, Nerlens Noel, Robert Covington)",4,0.000000